public final class Main {
	public static void main(String[] args) {
//		SolutionTester tester = new SolutionTester();
//		tester.testEP01();
//		tester.testEP02();
//		tester.testEP03();
//		tester.testEP04();
//		tester.testEP05();
//		tester.testEP06();
//		tester.testEP07();
//		tester.testEP08();
//		tester.testEP09();
//		tester.testEP10();
//		tester.testEP11();
//		tester.testEP12();
//		tester.testEP13();
//		tester.testEP14();
//		tester.testEP15();
//		tester.testEP16();
//		tester.testEP17();
//		tester.testEP18();
//		tester.testEP19();
//		tester.testEP20();
//		tester.testEP21();
//		tester.testEP22();
//		tester.testEP23();
//		System.out.println((new EP01()).run());
//		System.out.println((new EP02()).run()); 
//		System.out.println((new EP03()).run());
//		System.out.println((new EP04()).run());
//		System.out.println((new EP05()).run());
//		System.out.println((new EP06()).run());
//		System.out.println((new EP07()).run());
//		System.out.println((new EP08()).run()); 
//		System.out.println((new EP09()).run());
//		System.out.println((new EP10()).run());
//		System.out.println((new EP11()).run());
//		System.out.println((new EP12()).run()); 
//		System.out.println((new EP13()).run());
//		System.out.println((new EP14()).run());
//		System.out.println((new EP15()).run());
//		System.out.println((new EP16()).run());
//		System.out.println((new EP17()).run());
//		System.out.println((new EP18()).run());
//		System.out.println((new EP19()).run());
//		System.out.println((new EP20()).run());
//		System.out.println((new EP21()).run());
//		System.out.println((new EP22()).run());
//		System.out.println((new EP23()).run());
//		System.out.println((new EP24()).run());
		System.out.println((new EP25()).run());
	}
}
